import os
import base64
from datetime import datetime

def image_to_base64(image_path):
    """Converts an image file to a base64 string."""
    if not os.path.exists(image_path):
        return ""
    with open(image_path, "rb") as image_file:
        encoded_string = base64.b64encode(image_file.read()).decode('utf-8')
        ext = os.path.splitext(image_path)[1][1:]
        return f"data:image/{ext};base64,{encoded_string}"

def generate_html_report(complex_name, analysis_dir, plots, metadata=None):
    """Generates a standalone HTML report for the MD analysis."""
    
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MD Analysis Report - {complex_name}</title>
        <style>
            body {{
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 1000px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f4f7f6;
            }}
            header {{
                background-color: #2c3e50;
                color: white;
                padding: 20px;
                border-radius: 8px;
                margin-bottom: 30px;
                text-align: center;
            }}
            .card {{
                background: white;
                padding: 20px;
                margin-bottom: 20px;
                border-radius: 8px;
                box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            }}
            h2 {{
                color: #2c3e50;
                border-bottom: 2px solid #3498db;
                padding-bottom: 10px;
            }}
            .plot-container {{
                text-align: center;
                margin-top: 20px;
            }}
            .plot-container img {{
                max-width: 100%;
                height: auto;
                border: 1px solid #ddd;
                border-radius: 4px;
            }}
            .metadata-table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 10px;
            }}
            .metadata-table th, .metadata-table td {{
                padding: 12px;
                text-align: left;
                border-bottom: 1px solid #ddd;
            }}
            .metadata-table th {{
                background-color: #f8f9fa;
                width: 30%;
            }}
            .footer {{
                text-align: center;
                margin-top: 40px;
                font-size: 0.9em;
                color: #7f8c8d;
            }}
            @media print {{
                body {{ background-color: white; }}
                .card {{ box-shadow: none; border: 1px solid #eee; break-inside: avoid; }}
                header {{ background-color: #eee; color: black; border: 1px solid #ccc; }}
            }}
        </style>
    </head>
    <body>
        <header>
            <h1>Molecular Dynamics Analysis Report</h1>
            <p>Complex: <strong>{complex_name}</strong></p>
            <p>Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </header>

        <div class="card">
            <h2>System Information</h2>
            <table class="metadata-table">
    """
    
    if metadata:
        for key, value in metadata.items():
            html_content += f"<tr><th>{key}</th><td>{value}</td></tr>"
    else:
        html_content += f"<tr><th>Status</th><td>Analysis completed successfully</td></tr>"
        
    html_content += """
            </table>
        </div>
    """

    for plot_title, plot_path in plots.items():
        b64_img = image_to_base64(plot_path)
        if b64_img:
            html_content += f"""
            <div class="card">
                <h2>{plot_title}</h2>
                <div class="plot-container">
                    <img src="{b64_img}" alt="{plot_title}">
                </div>
            </div>
            """

    html_content += f"""
        <div class="footer">
            <p>Generated by MD Workflow Suite</p>
        </div>
    </body>
    </html>
    """

    report_path = os.path.join(analysis_dir, f"report_{complex_name}.html")
    with open(report_path, "w") as f:
        f.write(html_content)
    
    return report_path
