name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Downloader Docker image
      run: docker build . --file "downloader.Dockerfile" --tag custom-linux:latest
    - name: Build the Autodock GPU Docker image
      run: docker build . --file "autodock-gpu.dockerfile" --tag autodock-gpu:latest 
    - name: Build the QuickVina GPU Docker image
      run: docker build . --file "Dockerfile" --tag quickvina-gpu:latest
