name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jsphu
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Autodock GPU
        run: |
          cd ${{ github.workspace }}/containers
          docker build . --file "autodock-gpu.dockerfile" --tag autodock-gpu:latest

      - name: Build & Push Downloader
        run: |
          cd ${{ github.workspace }}/containers
          docker build . --file "downloader.dockerfile" --tag ghcr.io/${{ github.repository }}/downloader:latest
          docker push ghcr.io/${{ github.repository }}/downloader:latest

      - name: Build & Push QuickVina GPU
        run: |
          cd ${{ github.workspace }}/containers
          docker build . --file "quickvina-gpu.dockerfile" --tag ghcr.io/${{ github.repository }}/quickvina-gpu:latest
          docker push ghcr.io/${{ github.repository }}/quickvina-gpu:latest

      - name: Build & Push Vina GPU
        run: |
          cd ${{ github.workspace }}/containers
          docker build . --file "vina-gpu.dockerfile" --tag ghcr.io/${{ github.repository }}/vina-gpu:latest
          docker push ghcr.io/${{ github.repository }}/vina-gpu:latest
